---
title: "GERMS BioMark Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    css: www/styles.css
runtime: shiny
---

```{r setup, include=FALSE}
source("setup.R")
```

Inputs {.sidebar data-width=300}
=======================================================================

```{r}
# Input for Biomark file name
pickerInput(
  "biomark_file_choice",
  label = h4("BioMark file:"),
  choices = unique(all_biomark_runs$filename),
  selected = all_biomark_runs$filename[1],
  options = pickerOptions(
    liveSearch = TRUE
  )
)
```

```{r}
# Download buttons for selected BioMark csv
uiOutput("downloadUI")
```

```{r}
# Create the actual downloadButton
output$downloadUI <- renderUI({
  downloadButton("downBtn", "Download selected BioMark data", style = "width:100%;")
})

# Add download handling
output$downBtn <- downloadHandler(
  filename = function() {
    biomark_file_selected()
  },
  content = function(file) {
    write.csv(selected_run_data(), file, row.names = FALSE)
  }
)
```



```{r}
biomark_file_selected <- reactive(input$biomark_file_choice)

# Constructs the mongoDB query when the selected biomark file is changed
file_query <- reactive(
  paste0(
    '{"filename": "', biomark_file_selected(),'"}'
  )
)

## Update plotting info based on current file
current_biomark_run_measured_genes <- reactive(
    all_biomark_runs %>%
      filter(filename == biomark_file_selected()) %>%
      pull(genes_measured) %>% 
      unlist()
)

current_biomark_sample_names <- reactive(
    all_biomark_runs %>%
      filter(filename == biomark_file_selected()) %>%
      pull(sample_names) 
)

current_biomark_run_factors <- reactive(
  all_biomark_runs %>%
    filter(filename == biomark_file_selected()) %>%
    pull(factors) %>%
    unlist()
)

current_biomark_data_type <- reactive(
  all_biomark_runs %>%
    filter(filename == biomark_file_selected()) %>%
    pull(data_type)
)

# Use the open connection to get the selected dataset.
selected_run_data <- reactive(
  all_biomark_data_con$find(file_query()) %>%
    as_tibble() %>% 
    mutate(
      across(
        c(current_biomark_run_measured_genes()),
        as.numeric
      )
    )
)
```

# Run data

## Column

### Run data for `r renderText(biomark_file_selected())`

```{r}
renderDT(
  selected_run_data(),
  options = list(
    pageLength = 25
  )

)
```


# Heatmap

## Column

### Heatmap for `r renderText(biomark_file_selected())`

<div class="active-pane-options">
  <div>
  
```{r}
# Picker input for the grouping factor
default_value <- "Select sample to get started"

pickerInput(
  "grouping_factor",
  label = h4("Group by: "),
  choices = default_value,
  # selected = "This",
  options = pickerOptions(
    liveSearch = TRUE
  )
)
```

  </div>
  <div>

  <label class="control-label">
    <h4> Download... </h4>
  </label>
    
```{r}
uiOutput("download_heatmap_ui")
```

```{r}
output$download_heatmap_ui <- renderUI({
  downloadButton("download_heatmap_button", "Download Heatmap")
})

output$download_heatmap_button <- downloadHandler(
  # For PDF output, change this to "report.pdf"
  filename = "heatmap_plot.html",
  content = function(file) {
    # Copy the report file to a temporary directory before processing it, in
    # case we don't have write permissions to the current working dir (which
    # can happen when deployed).
    tempReport <- file.path(tempdir(), "heatmap_plot.Rmd")
    file.copy("rmd_templates/heatmap_plot.Rmd", tempReport, overwrite = TRUE)
    
    # Set up parameters to pass to Rmd document
    params <- list(
      grouping_factor = grouping_factor_picked(),
      file_name = biomark_file_selected(),
      biomark_data = selected_run_data(),
      sample_names = current_biomark_sample_names(),
      measured_genes = current_biomark_run_measured_genes(),
      biomark_data_type = current_biomark_data_type()
      
    )
    
    # Knit the document, passing in the `params` list, and eval it in a
    # child of the global environment (this isolates the code in the document
    # from the code in this app).
    rmarkdown::render(
      tempReport,
      output_file = file,
      params = params,
      envir = new.env(parent = globalenv())
    )
  }
)
```



  </div>
</div>

```{r}
# Update PickerInput choices
observeEvent(
  input$biomark_file_choice, {
    updatePickerInput(
      session = session,
      inputId = "grouping_factor",
      choices = current_biomark_run_factors(),
      selected = current_biomark_run_factors()[1]
    )
  }
)

grouping_factor_picked <- reactive(input$grouping_factor)
```

```{r}
HTML("<br><br>")

renderPlotly({
  # req(nrow(selected_run_data()) > 0)
  req(grouping_factor_picked() != default_value)
  
  p <-  selected_run_data() %>%
    pivot_longer(current_biomark_run_measured_genes()) %>%
    ggplot(aes(!!as.symbol(current_biomark_sample_names()), name, fill = value)) +
    # geom_tile(color = "#EEEEEE") +
    geom_tile(color = "black", size = 1) +
    facet_grid(~ get(input$grouping_factor), scales = "free") +
    labs(
      x = "",
      y = "",
      fill = current_biomark_data_type()
    ) +
    scale_y_discrete(limits = rev) +
    scale_fill_viridis_c(
      direction = -1,
      option = "magma"
    ) +
    theme(
      strip.text = element_markdown(size = 10, face = "bold"),
      strip.background = element_rect(size = 1, color = "black", fill = NA),
      panel.background = element_blank(),
      panel.grid = element_blank(),
      # panel.border = element_rect(color = "black", fill = NA),
      axis.text.x = element_blank(),
      axis.ticks = element_blank()
    ) 
  
  ggplotly(p, height = 800)
})
```

# All runs

## Column

### Summary data for all runs

```{r}
renderDT(
  datatable(
    all_biomark_runs %>% 
      select(-c(genes_measured, factors)) %>% 
      rename(genes_measured = nice_genes_measured, factors = nice_factors) %>% 
      select(filename, project_name, genes_measured, factors, data_type, uploaded_by),
    options = list(
      autoWidth = TRUE
    )
  )
)
```
